import { Header } from "../components/Header/header";
import { HeroSection } from "../components/HeroSection/herosection";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
<div className="flex flex-col min-h-screen">
      <head>
        <title>Cloudblocks | Distributed Servers  </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico" />
      </head>

      <main className="flex-grow">
        <div className="content-container">
                <Header />

          {/* Hero Section */}
          <div className="section">
            <HeroSection />
          </div>
          </div>
          </main>
          </div>
  );
}
